In [1]:
import pickle
import numpy as np
import pandas as pd


In [2]:
ohe_sex=pickle.load(open('F:\campusX\Model\ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('F:\campusX\Model\ohe_embarked.pkl','rb'))
clf=pickle.load(open('F:\campusX\Model\clf.pkl','rb'))

In [3]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked

test_input= np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [5]:
# For 'Sex' column (assuming it was fit with column name 'Sex')
test_input_sex = ohe_sex.transform(pd.DataFrame(test_input[:, 1].reshape(1, 1), columns=['Sex']))

In [6]:
# For 'Embarked' column (assuming it was fit with column name 'Embarked')
test_input_embarked = ohe_embarked.transform(pd.DataFrame(test_input[:, -1].reshape(1, 1), columns=['Embarked']))

C:\Users\risha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but OneHotEncoder was fitted without feature names
  warnings.warn(


In [7]:
test_input_sex

array([[0., 1.]])

In [8]:
test_input_embarked

array([[0., 0., 1.]])