In [2]:
import numpy as np
import pandas as pd

In [3]:
a=np.array(4)

In [4]:
a

array(4)

In [5]:
a.ndim

0

In [6]:
arr=np.array([1,2,3])

In [7]:
arr.ndim

1

In [8]:
b=np.array([[[2,3,3],
            [4,5,4],
            [6,7,8]]])

In [9]:
b.ndim

3

In [10]:
print(b)

[[[2 3 3]
  [4 5 4]
  [6 7 8]]]


In [11]:
# 2d matrices

mat=np.array([[2,3,3],
            [4,5,4],
            [6,7,8]])

In [12]:
mat.ndim


2

In [13]:
df=pd.read_csv("F:\campusX\messy_data.csv")

In [14]:
df.head(5)

Employee_ID Employee Name   Age Department Joining Date   Salary  \
0          101  Employee_101  52.0         HR     02/06/20    74776   
1          102  Employee_102  56.0      Sales     01/05/18      NaN   
2          103  Employee_103  35.0  Marketing     13/01/18    87947   
3          104  Employee_104  57.0    Finance     07/04/19      NaN   
4          105  Employee_105  28.0      Sales     18/02/17  INVALID   

              Address  
0   49 Example Street  
1  214 Example Street  
2  963 Example Street  
3   26 Example Street  
4  828 Example Street

In [15]:
pd.read_csv("F:\campusX\messy_data.csv").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Employee_ID    100 non-null    int64  
 1   Employee Name  99 non-null     object 
 2   Age            96 non-null     float64
 3   Department     93 non-null     object 
 4   Joining Date   99 non-null     object 
 5   Salary         48 non-null     object 
 6   Address        99 non-null     object 
dtypes: float64(1), int64(1), object(5)
memory usage: 5.6+ KB


In [16]:
#before this joing data is object that means it string 

pd.read_csv("F:\campusX\messy_data.csv",parse_dates=['Joining Date']).info()
# Now it will int type we can use all the function on it

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Employee_ID    100 non-null    int64         
 1   Employee Name  99 non-null     object        
 2   Age            96 non-null     float64       
 3   Department     93 non-null     object        
 4   Joining Date   99 non-null     datetime64[ns]
 5   Salary         48 non-null     object        
 6   Address        99 non-null     object        
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 5.6+ KB


C:\Users\risha\AppData\Local\Temp\ipykernel_9728\1374750699.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv("F:\campusX\messy_data.csv",parse_dates=['Joining Date']).info()


In [17]:
df.head()

Employee_ID Employee Name   Age Department Joining Date   Salary  \
0          101  Employee_101  52.0         HR     02/06/20    74776   
1          102  Employee_102  56.0      Sales     01/05/18      NaN   
2          103  Employee_103  35.0  Marketing     13/01/18    87947   
3          104  Employee_104  57.0    Finance     07/04/19      NaN   
4          105  Employee_105  28.0      Sales     18/02/17  INVALID   

              Address  
0   49 Example Street  
1  214 Example Street  
2  963 Example Street  
3   26 Example Street  
4  828 Example Street

###Convererters

In [18]:
def rename(name):
    if name=="HR":
        return "Human_Resouce"
    else:
        return name

In [19]:
rename("HR")

'Human_Resouce'

In [20]:
pd.read_csv("F:\campusX\messy_data.csv",converters={'Department':rename})

Employee_ID Employee Name   Age     Department Joining Date   Salary  \
0           101  Employee_101  52.0  Human_Resouce     02/06/20    74776   
1           102  Employee_102  56.0          Sales     01/05/18      NaN   
2           103  Employee_103  35.0      Marketing     13/01/18    87947   
3           104  Employee_104  57.0        Finance     07/04/19      NaN   
4           105  Employee_105  28.0          Sales     18/02/17  INVALID   
..          ...           ...   ...            ...          ...      ...   
95          196  Employee_196  34.0             IT     28/02/22      NaN   
96          197  Employee_197  60.0        Finance     08/03/19  INVALID   
97          198  Employee_198  31.0  Human_Resouce     01/07/21      NaN   
98          199  Employee_199  46.0        Finance     20/09/19      NaN   
99          200  Employee_200  59.0          Sales     21/01/20    95964   

               Address  
0    49 Example Street  
1   214 Example Street  
2   963 Example Street  
3    26 Example Street  
4   828 Example Street  
..                 ...  
95  537 Example Street  
96  548 Example Street  
97  775 Example Street  
98  527 Example Street  
99  183 Example Street  

[100 rows x 7 columns]

In [21]:
# change in NAN

# pd.read_csv("F:\campusX\messy_data.csv",na_values=['101'])

In [22]:
df=pd.read_csv("F:\campusX\messy_data.csv")

In [23]:
print(df)

    Employee_ID Employee Name   Age Department Joining Date   Salary  \
0           101  Employee_101  52.0         HR     02/06/20    74776   
1           102  Employee_102  56.0      Sales     01/05/18      NaN   
2           103  Employee_103  35.0  Marketing     13/01/18    87947   
3           104  Employee_104  57.0    Finance     07/04/19      NaN   
4           105  Employee_105  28.0      Sales     18/02/17  INVALID   
..          ...           ...   ...        ...          ...      ...   
95          196  Employee_196  34.0         IT     28/02/22      NaN   
96          197  Employee_197  60.0    Finance     08/03/19  INVALID   
97          198  Employee_198  31.0         HR     01/07/21      NaN   
98          199  Employee_199  46.0    Finance     20/09/19      NaN   
99          200  Employee_200  59.0      Sales     21/01/20    95964   

               Address  
0    49 Example Street  
1   214 Example Street  
2   963 Example Street  
3    26 Example Street  
4   828 Ex